server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

#swagger config
springdoc:
  api-docs:
    enabled: true

spring:
  application:
    name: Job-Hunting-Platform
  messages:
    encoding: UTF-8
    basename: messages
    fallback-to-system-locale: false
  datasource:
    url: jdbc:postgresql://localhost:5432/job_hunting_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 30000
    batch:
      jdbc:
        initialize-schema: "always"
      job:
        enabled: false
  jpa:
    hibernate:
    show-sql: true

  app:
    cors:
      allowed-origins: '*'
      allowed-methods: '*'
      allowed-headers: '*'
      exposed-headers: 'Authorization,Link,X-Total-Count,Set-Cookie,X-Auth-Token,x-api-key'
      max-age: 1800
    jwt:
      password: d2Fzd29uZGVyZmlsbG5vaXNlc3BsaXRjcm93ZHNob3R1bmRlcmFycm93dGhyb3VnaG8=
      expiration-time: 8.64e+7